"""empty message

Revision ID: fa769b51d06a
Revises: 26fc96d7d897
Create Date: 2022-05-30 01:53:30.144162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa769b51d06a'
down_revision = '26fc96d7d897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('available_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('artists', sa.Column('available_to', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'available_to')
    op.drop_column('artists', 'available_from')
    # ### end Alembic commands ###
